FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:bullseye

RUN install_packages \
    libcamera-apps-lite \
    v4l-utils

WORKDIR /usr/src/app

COPY start.sh ./

RUN chmod +x start.sh

CMD ["sh","./start.sh"]